# Generated by Django 6.0.4 on 2026-04-29 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoasis', '0003_informe_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('area_asignada', models.CharField(choices=[('pisos_1', 'Pisos 1'), ('pisos_2', 'Pisos 2'), ('pisos_3', 'Pisos 3'), ('patios', 'Patios y exteriores'), ('banos', 'Baños'), ('cafeteria', 'Cafetería'), ('general', 'General')], default='general', max_length=30)),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('completo', 'Jornada completa')], default='manana', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas_generales', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Personal de Aseo',
                'verbose_name_plural': 'Personal de Aseo',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='docente',
            name='grados_a_cargo',
            field=models.CharField(blank=True, help_text='Ej: 6A, 7B, 8A', max_length=200),
        ),
        migrations.AlterField(
            model_name='informe',
            name='contenido',
            field=models.TextField(verbose_name='Análisis e impresión psicológica'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='recomendaciones',
            field=models.TextField(blank=True, verbose_name='Recomendaciones'),
        ),
    ]
